# Generated by Django 4.2.1 on 2023-05-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('eighth_price', models.IntegerField(blank=True, null=True)),
                ('quarter_price', models.IntegerField(blank=True, null=True)),
                ('half_price', models.IntegerField(blank=True, null=True)),
                ('ounce_price', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=50)),
                ('tac', models.FloatField(blank=True, null=True)),
                ('thc', models.FloatField(blank=True, null=True)),
                ('cbd', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='flower',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='category',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
